/* Generated By:JavaCC: Do not edit this line. SGFConstants.java */
package com.github.mccxj.go.sgf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SGFConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMI = 5;
  /** RegularExpression Id. */
  int OPEN = 6;
  /** RegularExpression Id. */
  int CLOSE = 7;
  /** RegularExpression Id. */
  int NAME = 8;
  /** RegularExpression Id. */
  int VALUE = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<NAME>",
    "<VALUE>",
  };

}
